import type { CardId } from '@/src/utils/cardMap';

type Descriptions = Record<CardId, string>;
const ptDescriptions: Descriptions = {
  chains: 'Prende um rival com correntes e prejudica sua corrida.',
  tnt: 'Larga uma TNT explosiva na pista.',
  oil_spit: 'Derrama óleo atrás de você. Quem passar pela poça derrapa e perde velocidade.',
  magnet: 'Atrai por 5s engrenagens, peças, sprays e CHIPs próximos. Não cria recursos.',
  emp_pulse: 'Interfere em um rival por 2s, cancela o nitro ativo e bloqueia "Nitro Power" e "Shield". Não causa dano.',
  swap: 'Troca sua posição com a de outro corredor.',
  slow_slow: 'Reduz temporariamente a velocidade dos rivais.',
  blind: 'Prejudica a visão de um adversário.',
  bullet: 'Lança um projétil guiado contra um rival.',
  tornado: 'Envia um tornado contra adversários à frente.',
  bubble_lift: 'Suspende um rival numa bolha por alguns instantes.',
  nitro_power: 'Concede um impulso temporário de velocidade.',
  shield: 'Bloqueia um ataque recebido.',
  armor: 'Reforça a proteção do veículo.',
  quick_repair: 'Recupera sua resistência durante a corrida.',
  ghost: 'Permite evitar ataques enquanto o efeito está ativo.',
  second_chance: 'Concede uma segunda chance após ser eliminado.',
};
const enDescriptions: Descriptions = {
  chains: 'Snare a rival with chains and disrupt their race.',
  tnt: 'Drop an explosive TNT crate on the track.',
  oil_spit: 'Leave an oil slick behind. Rivals who cross it skid and slow down.',
  magnet: 'Pull nearby gears, parts, sprays and CHIPS towards you for 5s. Does not create loot.',
  emp_pulse: 'Jam one rival for 2s, cancel active nitro, and block "Nitro Power" and "Shield". Deals no damage.',
  swap: 'Swap positions with another racer.',
  slow_slow: 'Temporarily slow down rivals.',
  blind: 'Obstruct a rival’s vision.',
  bullet: 'Fire a guided projectile at a rival.',
  tornado: 'Send a tornado towards racers ahead.',
  bubble_lift: 'Lift a rival into a bubble briefly.',
  nitro_power: 'Gain a temporary speed boost.',
  shield: 'Block an incoming attack.',
  armor: 'Reinforce your vehicle’s protection.',
  quick_repair: 'Recover endurance during the race.',
  ghost: 'Evade attacks while the effect is active.',
  second_chance: 'Get another chance after elimination.',
};
const esDescriptions: Descriptions = {
  chains: 'Atrapa a un rival con cadenas y perjudica su carrera.',
  tnt: 'Deja una caja de TNT explosiva en la pista.',
  oil_spit: 'Deja una mancha de aceite detrás. Quien la pise derrapa y pierde velocidad.',
  magnet: 'Atrae durante 5 s engranajes, piezas, sprays y CHIPS cercanos. No crea recursos.',
  emp_pulse: 'Interfiere a un rival durante 2 s, cancela el nitro activo y bloquea "Nitro Power" y "Shield". No causa daño.',
  swap: 'Intercambia posiciones con otro corredor.',
  slow_slow: 'Reduce temporalmente la velocidad de los rivales.',
  blind: 'Dificulta la visión de un rival.',
  bullet: 'Lanza un proyectil guiado contra un rival.',
  tornado: 'Envía un tornado hacia los corredores de delante.',
  bubble_lift: 'Suspende brevemente a un rival en una burbuja.',
  nitro_power: 'Obtén un impulso temporal de velocidad.',
  shield: 'Bloquea un ataque recibido.',
  armor: 'Refuerza la protección de tu vehículo.',
  quick_repair: 'Recupera resistencia durante la carrera.',
  ghost: 'Evita ataques mientras dure el efecto.',
  second_chance: 'Consigue otra oportunidad tras ser eliminado.',
};
export const DECK_STORE_COPY = {
  pt: {
    title: 'WILD CARD STORE', subtitle: 'AMPLIE SEU ARSENAL', open: 'LOJA DE CARTAS',
    chips: 'CHIPS', all: 'TODAS', attack: 'ATAQUE', defense: 'DEFESA',
    owned: 'ADQUIRIDA', buy: 'COMPRAR', missing: 'FALTAM',
    level: 'NÍVEL', levelNeeded: 'DESBLOQUEIA NO NÍVEL',
    collection: 'COLEÇÃO', shop: 'CATÁLOGO', cardCost: 'CUSTO NA CORRIDA',
    price: 'PREÇO DA CARTA', deck: 'IR PARA DECKS', select: 'SELECIONE UMA CARTA',
    selectHint: 'Escolha uma carta do catálogo para visualizar e comprar.',
    ready: 'CARTA DISPONÍVEL', buyTitle: 'Confirmar compra',
    cancel: 'CANCELAR', confirm: 'COMPRAR', successTitle: 'Carta desbloqueada!',
    noProfile: 'Perfil indisponível. Entre novamente no jogo.',
    insufficient: 'CHIPS insuficientes.', already: 'Essa carta já está no seu inventário.',
    locked: 'Seu nível ainda não permite esta compra.', failed: 'Não foi possível concluir a compra.',
    buyQuestion: (name: string, price: number) => `Comprar ${name} por ${price} CHIPS?`,
    success: (name: string) => `${name} foi adicionada ao seu inventário. Agora você pode equipá-la em Decks.`,
    descriptions: ptDescriptions,
  },
  en: {
    title: 'WILD CARD STORE', subtitle: 'EXPAND YOUR ARSENAL', open: 'CARD STORE',
    chips: 'CHIPS', all: 'ALL', attack: 'ATTACK', defense: 'DEFENSE',
    owned: 'OWNED', buy: 'BUY', missing: 'NEEDED',
    level: 'LEVEL', levelNeeded: 'UNLOCKS AT LEVEL',
    collection: 'COLLECTION', shop: 'CATALOG', cardCost: 'IN-RACE COST',
    price: 'CARD PRICE', deck: 'GO TO DECKS', select: 'SELECT A CARD',
    selectHint: 'Choose a card from the catalog to inspect and buy it.',
    ready: 'CARD AVAILABLE', buyTitle: 'Confirm purchase',
    cancel: 'CANCEL', confirm: 'BUY', successTitle: 'Card unlocked!',
    noProfile: 'Profile unavailable. Please sign back into the game.',
    insufficient: 'Not enough CHIPS.', already: 'You already own this card.',
    locked: 'Your level is too low to purchase this card.', failed: 'Could not complete the purchase.',
    buyQuestion: (name: string, price: number) => `Buy ${name} for ${price} CHIPS?`,
    success: (name: string) => `${name} was added to your collection. You can equip it in Decks.`,
    descriptions: enDescriptions,
  },
  es: {
    title: 'WILD CARD STORE', subtitle: 'AMPLÍA TU ARSENAL', open: 'TIENDA DE CARTAS',
    chips: 'CHIPS', all: 'TODAS', attack: 'ATAQUE', defense: 'DEFENSA',
    owned: 'ADQUIRIDA', buy: 'COMPRAR', missing: 'FALTAN',
    level: 'NIVEL', levelNeeded: 'SE DESBLOQUEA EN NIVEL',
    collection: 'COLECCIÓN', shop: 'CATÁLOGO', cardCost: 'COSTE EN CARRERA',
    price: 'PRECIO DE LA CARTA', deck: 'IR A MAZOS', select: 'ELIGE UNA CARTA',
    selectHint: 'Selecciona una carta del catálogo para verla y comprarla.',
    ready: 'CARTA DISPONIBLE', buyTitle: 'Confirmar compra',
    cancel: 'CANCELAR', confirm: 'COMPRAR', successTitle: '¡Carta desbloqueada!',
    noProfile: 'Perfil no disponible. Vuelve a iniciar sesión.',
    insufficient: 'No tienes suficientes CHIPS.', already: 'Ya tienes esta carta.',
    locked: 'Tu nivel es insuficiente para comprar esta carta.', failed: 'No se pudo completar la compra.',
    buyQuestion: (name: string, price: number) => `¿Comprar ${name} por ${price} CHIPS?`,
    success: (name: string) => `${name} se añadió a tu colección. Puedes equiparla en Mazos.`,
    descriptions: esDescriptions,
  },
};
export function getDeckStoreCopy(language: string) {
  const code = language.toLowerCase();
  return code.startsWith('pt') ? DECK_STORE_COPY.pt : code.startsWith('es') ? DECK_STORE_COPY.es : DECK_STORE_COPY.en;
}
